---
name: CI

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v.*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: fish-shop/install-fish-shell@v2
      - uses: jdx/mise-action@v2
      - run: mise run test

  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-shop/install-fish-shell@v2
      - uses: fish-shop/syntax-check@v2

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-shop/install-fish-shell@v2
      - uses: fish-shop/indent-check@v2

  mega-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oxsecurity/megalinter/flavors/documentation@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
